coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 60%

  ignore:
    - "test/**/*"
    - "app/**/*"
    - "build/**/*"
    - "**/*.mod"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
