! Regression test for issue #2394: uppercase PURE FUNCTION with allocatable result
PROGRAM UPPERCASE_ALLOCATABLE_FUNCTION
    IMPLICIT NONE

    CHARACTER(LEN=:), ALLOCATABLE :: STR
    STR = "ABCdef"
    IF (STR /= "ABCdef" .OR. LEN(STR) /= 6) STOP 1
END PROGRAM UPPERCASE_ALLOCATABLE_FUNCTION
