! Performance test: many statement IFs should parse efficiently
! This file tests the fix for quadratic array growth in IF parsing
program many_statement_ifs
    implicit none
    integer :: acc = 0
    if (acc == 0) acc = acc + 1
    if (acc == 1) acc = acc + 1
    if (acc == 2) acc = acc + 1
    if (acc == 3) acc = acc + 1
    if (acc == 4) acc = acc + 1
    if (acc == 5) acc = acc + 1
    if (acc == 6) acc = acc + 1
    if (acc == 7) acc = acc + 1
    if (acc == 8) acc = acc + 1
    if (acc == 9) acc = acc + 1
    if (acc == 10) acc = acc + 1
    if (acc == 11) acc = acc + 1
    if (acc == 12) acc = acc + 1
    if (acc == 13) acc = acc + 1
    if (acc == 14) acc = acc + 1
    if (acc == 15) acc = acc + 1
    if (acc == 16) acc = acc + 1
    if (acc == 17) acc = acc + 1
    if (acc == 18) acc = acc + 1
    if (acc == 19) acc = acc + 1
    if (acc == 20) acc = acc + 1
    if (acc == 21) acc = acc + 1
    if (acc == 22) acc = acc + 1
    if (acc == 23) acc = acc + 1
    if (acc == 24) acc = acc + 1
    if (acc == 25) acc = acc + 1
    if (acc == 26) acc = acc + 1
    if (acc == 27) acc = acc + 1
    if (acc == 28) acc = acc + 1
    if (acc == 29) acc = acc + 1
    if (acc == 30) acc = acc + 1
    if (acc == 31) acc = acc + 1
    if (acc == 32) acc = acc + 1
    if (acc == 33) acc = acc + 1
    if (acc == 34) acc = acc + 1
    if (acc == 35) acc = acc + 1
    if (acc == 36) acc = acc + 1
    if (acc == 37) acc = acc + 1
    if (acc == 38) acc = acc + 1
    if (acc == 39) acc = acc + 1
    if (acc == 40) acc = acc + 1
    if (acc == 41) acc = acc + 1
    if (acc == 42) acc = acc + 1
    if (acc == 43) acc = acc + 1
    if (acc == 44) acc = acc + 1
    if (acc == 45) acc = acc + 1
    if (acc == 46) acc = acc + 1
    if (acc == 47) acc = acc + 1
    if (acc == 48) acc = acc + 1
    if (acc == 49) acc = acc + 1
    if (acc == 50) acc = acc + 1
    if (acc == 51) acc = acc + 1
    if (acc == 52) acc = acc + 1
    if (acc == 53) acc = acc + 1
    if (acc == 54) acc = acc + 1
    if (acc == 55) acc = acc + 1
    if (acc == 56) acc = acc + 1
    if (acc == 57) acc = acc + 1
    if (acc == 58) acc = acc + 1
    if (acc == 59) acc = acc + 1
    if (acc == 60) acc = acc + 1
    if (acc == 61) acc = acc + 1
    if (acc == 62) acc = acc + 1
    if (acc == 63) acc = acc + 1
    if (acc == 64) acc = acc + 1
    if (acc == 65) acc = acc + 1
    if (acc == 66) acc = acc + 1
    if (acc == 67) acc = acc + 1
    if (acc == 68) acc = acc + 1
    if (acc == 69) acc = acc + 1
    if (acc == 70) acc = acc + 1
    if (acc == 71) acc = acc + 1
    if (acc == 72) acc = acc + 1
    if (acc == 73) acc = acc + 1
    if (acc == 74) acc = acc + 1
    if (acc == 75) acc = acc + 1
    if (acc == 76) acc = acc + 1
    if (acc == 77) acc = acc + 1
    if (acc == 78) acc = acc + 1
    if (acc == 79) acc = acc + 1
    if (acc == 80) acc = acc + 1
    if (acc == 81) acc = acc + 1
    if (acc == 82) acc = acc + 1
    if (acc == 83) acc = acc + 1
    if (acc == 84) acc = acc + 1
    if (acc == 85) acc = acc + 1
    if (acc == 86) acc = acc + 1
    if (acc == 87) acc = acc + 1
    if (acc == 88) acc = acc + 1
    if (acc == 89) acc = acc + 1
    if (acc == 90) acc = acc + 1
    if (acc == 91) acc = acc + 1
    if (acc == 92) acc = acc + 1
    if (acc == 93) acc = acc + 1
    if (acc == 94) acc = acc + 1
    if (acc == 95) acc = acc + 1
    if (acc == 96) acc = acc + 1
    if (acc == 97) acc = acc + 1
    if (acc == 98) acc = acc + 1
    if (acc == 99) acc = acc + 1
    print *, acc
end program many_statement_ifs
